### ISSUE TITLE
Update Twitter

### ISSUE THREAD

**Issue by zutrinken** [criticalmaps/criticalmaps-android#252] opened 2019-04-17 06:26 UTC
<table>
<tr>
<th>current</th>
<th>new (dark)</th>
<th>new (light)</th>
</tr>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/888679/56265660-684cfb00-60ea-11e9-9414-bff7277234b5.png" width="240" />
</td>
<td>
<img src="https://user-images.githubusercontent.com/888679/67844775-a5b12d00-fafe-11e9-9e90-a2eaa13df364.png" width="240" />
</td>
<td>
<img src="https://user-images.githubusercontent.com/888679/67844776-a649c380-fafe-11e9-80e5-f12c01e9f32e.png" width="240" />
</td>
</tr>
</table>

**Comment by askarsyzdykov** [comment] 2019-10-30 07:32
Is it confirmed design? I could resolve this issue

**Comment by cbalster** [comment] 2019-10-30 07:55
@askarsyzdykov Sure, go ahead!
I just to minor questions/remarks from my side @zutrinken can maybe give a suggestion for, before you start:
1) When we no longer show the date of the tweet and the time, what should be displayed if a tweet is not from today? Just the date?
2) Should we really only show the handle and not also the username? I think it's helpful to show both since a lot of times they are not identical. Another option might be to rather just show the username instead of the handle, since this is also the more prominent one in the twitter client.
3) I would like to keep the "+" FAB to open the twitter app for a new tweet. Thoughts on that?

Below is a screenshot of the current UI for reference:
![image](https://user-images.githubusercontent.com/9266843/67838764-5e24a400-faf2-11e9-951f-df41aeddcc8d.png)

**Comment by zutrinken** [comment] 2019-10-30 09:25
@askarsyzdykov @cbalster Designs are updated

1. Dates should be relative like on iOS (3 min, 2h, 1 d, 23. Jan).
2. Also added the username. The handle will be truncated if it's too long. 
3. Is it possible to just show the button if a twitter client is installed? Else I wouldn't show it, since it implements you could tweet inside our app.

**Comment by askarsyzdykov** [comment] 2019-10-30 09:47
@zutrinken 1,2 ok. 3. If no Twitter app on a device, then a default browser will be opened

**Comment by cbalster** [comment] 2019-10-30 09:54
@zutrinken nice, thanks!

Regarding the implementation: I would suggest only doing the dark design
for now. The dark/light mode thing is a ropic of it's own and has to be
addressed at the app level.
Thank you!

**Comment by askarsyzdykov** [comment] 2019-10-30 12:27
@zutrinken is there any tool to view design (margins, font size, etc), e.g Figma, Invision?

**Comment by zutrinken** [comment] 2019-10-30 12:51
@askarsyzdykov yes, Invision. You should have received an invite ...

**Comment by zutrinken** [comment] 2019-10-30 15:58
Interesting. I don't think we need them. A simple placeholder (gray circle) would be enough imo.

**Comment by askarsyzdykov** [comment] 2019-10-31 05:48
@cbalster what about Kotlin in this project? :)

**Comment by askarsyzdykov** [comment] 2019-10-31 06:47
Is the server down? @cbalster @stephanlindauer 

`
Caused by: java.net.SocketTimeoutException: failed to connect to settings.crashlytics.com/107.22.184.87 (port 443) from **** (port ****) after 10000ms
        at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
        at libcore.io.IoBridge.connect(IoBridge.java:129)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:145)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
        at io.fabric.sdk.android.services.network.HttpRequest.code(SourceFile:1357)
        at io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall.handleResponse(SourceFile:104) 
        at io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall.invoke(SourceFile:88) 
        at io.fabric.sdk.android.services.settings.DefaultSettingsController.loadSettingsData(SourceFile:93) 
        at io.fabric.sdk.android.services.settings.DefaultSettingsController.loadSettingsData(SourceFile:70) 
        at io.fabric.sdk.android.services.settings.Settings.loadSettingsData(SourceFile:156) 
        at io.fabric.sdk.android.Onboarding.retrieveSettingsData(SourceFile:128) 
        at io.fabric.sdk.android.Onboarding.doInBackground(SourceFile:100) 
        at io.fabric.sdk.android.Onboarding.doInBackground(SourceFile:46) 
        at io.fabric.sdk.android.InitializationTask.doInBackground(SourceFile:63) 
        at io.fabric.sdk.android.InitializationTask.doInBackground(SourceFile:28) 
        at io.fabric.sdk.android.services.concurrency.AsyncTask$2.call(SourceFile:311) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) `

**Comment by stephanlindauer** [comment] 2019-10-31 11:18
yes we unfortunately had a downtime tonight. i am in the process of moving to new infrastructure that should fix this in the future.

**Comment by cbalster** [comment] 2019-11-02 21:12
> @cbalster what about Kotlin in this project? :)

I think for new files or major changes in existing ones, using Kotlin is fine 👍.
I wouldn't necessarily start rewriting existing stuff, just to migrate it Kotlin.

**Closed** 2019-11-03 11:06 UTC
Labels: UI
